### ISSUE TITLE
Clarify description of "-portal" parameter in publish-to-mashery recipe

### ISSUE THREAD

**Issue by rkiesler1** [TIBCOSoftware/mashling-recipes#23]
A simple description like "the portal" does not inform the user what this parameter is used for or the expected value. The example `-portal PORTAL_URL` further confuses because the value expected is a hostname, not a URL. If you specify an actual URL like "http://rkdemo.mashery.com", you get back an error message stating that "Property '//rkdemo.mashery.com' is not a valid port number."

The value entered for this parameter is used to set the hostname of the public endpoint (traffic manager) and should be something like "<name>.api.mashery.com", e.g., "rkdemo.api.mashery.com"

**Comment by galois17** [comment]
That's true..thanks

**Comment by galois17** [comment]
A pull request has been made for this change.
