### ISSUE TITLE
Recipes registry should be more informative and published

### ISSUE THREAD

**Issue by nanoscale-randy** [TIBCOSoftware/mashling-recipes#27]
Need a separate recipe data source to serve manifest, binaries, and associated media (such as recipe icons).

Registry JSON should contain a list of available recipes with rich information about them, such as name and description, the URLs of associated binaries and accompanying media.  This JSON should be published on the web alongside the recipes themselves.  Perhaps at `recipes.mashling.io`?

Additional discussion here:
https://github.com/TIBCOSoftware/mashling-io/issues/116

**Comment by jpollock** [comment]
An api managed by mashery?

**Comment by nanoscale-randy** [comment]
I think the simplest path forward is to make a few tweaks to the current recipe release process.  Currently, recipes are built and pushed to a private S3 bucket.  That bucket could be exposed publicly via a URL such as, perhaps, `recipes.mashling.io`.  A better, more information-rich registry JSON should also be pushed into the bucket at build time.  From my perspective, this is the simplest, lowest-cost approach to solve the problem at this time.  A full API may not be necessary yet.

**Comment by jpark800** [comment]
Pre-built recipes to be shared with public are available at mashling.io. S3 bucket is the internal staging mechanism. A user should be able to build the recipe from the JSON rather easily if not available on mashling.io.

**Comment by nanoscale-randy** [comment]
@jpark800 The original request was to have the website _dynamically load the list of available recipes_, such that when new recipes are published they become available immediately.  This means that production recipe storage needs to be separated from the website.  We need a recipe data source for the website.  However, the website is only one of any number of potential consumers of the list of available recipes.

The website's current relationship to recipes and their associated metadata is profoundly ad hoc.  The website reads recipes from the S3 bucket at site build time, makes a bunch of assumptions and inferences that are guaranteed to one day break, generates its own local recipe data because the source manifest doesn't contain sufficient information, and serves up copies of the binary files.  It's taking on the responsibilities of what should be its own, first class data service.  A new S3 bucket exposed at its own URL is the easiest way to realize such a service given current architecture.

The original request is here:  https://github.com/TIBCOSoftware/mashling-io/issues/116

**Comment by jpark800** [comment]
Not convinced that a separate website is necessary to host the full recipe data and the binaries. The former is available on mashling-recipes repo and the latter is available from mashling.io. We can have a discussion on TIBCOSoftware/mashling-io#116 to find a resolution for that separately.
