### ISSUE TITLE
FATAL: command "build" failed import "golang.org/x/sys/windows"

### ISSUE THREAD

**Issue by ashdatla** [TIBCOSoftware/mashling-recipes#34]
Hi,

I am currently facing an issue after cloning a recipe and building the gateway. The following error shows up at the final steps of the build process and the Build folder fails to get created. 

FATAL: command "build" failed: failed to resolve import path "mqtt-gateway": import "golang.org/x/sys/windows": not found: CreateFile C:\Users\Administrator\Desktop\Mashling\mashli
ng-recipes\recipes\mqtt-gateway\mqtt-gateway\src\golang.org\x\sys\windows: The system cannot find the path specified.

I have set the gopath in my machine to C:\Users\Administrator\Desktop\Mashling
Installed gb build tool
Installed go 
Installed Mashling CLI 
Setup the environment path variable to include Mashling bin folder. 

The same issue occurred with other builds as well like the mqtt-lambda-tci recipe as well. 

Command run: mashling create -f mqtt-gateway.json mqtt-gateway

Thanks,
Ashwin

**Comment by rameshpolishetti** [comment]
@ashdatla Seems it is because of recent manifest changes. Could you please insert below snippet to ..._mqtt-gateway\manifest_ file and re run _mashling create -f mqtt-gateway.json mqtt-gateway_

after line# 341 insert:
               _{
			"importpath": "golang.org/x/sys/unix",
			"repository": "https://go.googlesource.com/sys",
			"revision": "75813c647272dd855bda156405bf844a5414f5bf",
			"branch": "master",
			"path": "/windows"
		},_

**Comment by ashdatla** [comment]
Thanks for the quick response. This fix worked and I am able to build the gw on my windows AMI. 

added the following lines: 
{
"importpath": "golang.org/x/sys/windows",
"repository": "https://go.googlesource.com/sys",
"revision": "75813c647272dd855bda156405bf844a5414f5bf",
"branch": "master",
"path": "/windows"
},
