### ISSUE TITLE
Secure Rest Gateway with Basic Auth is not working properly when built locally

### ISSUE THREAD

**Issue by ykalidin** [TIBCOSoftware/mashling-recipes#41]
**Steps:**

git clone https://github.com/TIBCOSoftware/mashling-recipes
cd mashling-recipes/recipes/secure-rest-gateway-with-basic-auth
Create the mashling app using the given secure-rest-gateway-with-basic-auth.json
Create a password.txt file with the below text:
foo:bar
**Run the App, an error should be logged that BASIC_AUTH_FILE is not set. But no error is seen.**

Now, set BASIC_AUTH_FILE = (Path to password.txt)
For valid user "curl -X GET http://foo:bar@localhost:9096/pets/3" gives success response.
**But for invalid user "curl -X GET http://foo:wrongpassword@localhost:9096/pets/3" also the same success response is seen.**

**Comment by rameshpolishetti** [comment]
Issue got fixed at commit hash bf48b7c49ed34dbac1f2eaed5f59425f846d9a6c
