### ISSUE TITLE
Istio recipe not working with reference flow.json

### ISSUE THREAD

**Issue by LakshmiMekala** [TIBCOSoftware/mashling-recipes#83]
Istio recipes is throwing failed to load reference istioflow.json EOF error.

**Comment by LakshmiMekala** [comment]
@pointlander By mentioning flow as github reference recipe is breaking.

**Comment by jpark800** [comment]
@LakshmiMekala The usage of the file reference is a fine solution. But if an error is thrown while executing the current recipe,  add the reproduction steps with the error outputs observed.

**Comment by LakshmiMekala** [comment]
Verified istio recipe with istio-1.0.1 version and observed that it is working fine.

Hence closing the issue
